export const products = [
  {
    sort: 1,
    productName: "Liposome",
    description: "ما هو الليبوسوم  هو هو هو؟",
    img: "assets/img/liposome.jpeg",
    category: "Chemicals",
    details: `الليبوسوم هو تركيب كروي صغير مكوّن من طبقات دهنية، يُستخدم لنقل المواد داخل الخلايا. يدخل في الصناعات الدوائية ومستحضرات التجميل لأنه يحسّن من امتصاص المكونات الفعالة.`,
  },
  {
    sort: 2,
    productName: "Collodion",
    description: "كولوديون مرن - U.S.P",
    img: "assets/img/colodion.jpeg",
    category: "Chemicals",
    details: `مادة سائلة تُستخدم لتغطية الجروح الصغيرة. تشكّل طبقة رقيقة مرنة عند جفافها، وتُستخدم في تثبيت الضمادات أو تغطية الأدوية على الجلد.`,
  },
  {
    sort: 3,
    productName: "Polycitra",
    description: "مزيج من السيترات لعلاج الحصوات",
    img: "assets/img/wintergreen.jpeg",
    category: "Chemicals",
    details: `يُستخدم لتقليل حموضة البول ومنع تكوّن حصى الكلى، ويُوصف أحيانًا لعلاج مشاكل التمثيل الغذائي الناتجة عن أمراض الكلى.`,
  },
  {
    sort: 4,
    productName: "Citric acid",
    description: "مُعقم نهائي لأجهزة غسيل الكلى",
    img: "assets/img/ment.jpg",
    category: "Chemicals",
    details: `حمض الستريك بنسبة 50%، يُستخدم لتعقيم الأجهزة الطبية وخاصة آلات غسيل الكلى. يمتاز بفعاليته كمادة تنظيف وتعقيم طبي.`,
  },
  {
    sort: 5,
    productName: "Citronella Oil",
    description: "زيت السترونيلا",
    img: "assets/img/coaltar.jpeg",
    category: "natural-oils",
    details: `زيت عطري طبيعي يُستخدم كمضاد للبعوض وله خصائص مطهّرة. يدخل في صناعة العطور ومنتجات العناية بالبشرة.`,
  },
  {
    sort: 6,
    productName: "Rose Water",
    description: "مياه الورد الطبيعية",
    img: "assets/img/ward.jpeg",
    category: "natural-oils",
    details: `تُستخدم لتنقية البشرة وترطيبها. تدخل في صناعة مستحضرات التجميل والوصفات الطبيعية للعناية بالوجه.`,
  },
  {
    sort: 7,
    productName: "Argan Oil",
    description: "زيت الأرغان المغربي",
    img: "assets/img/argan.jpg",
    category: "natural-oils",
    details: `يُستخدم لترطيب الشعر والبشرة ويحتوي على فيتامين E. من أكثر الزيوت شهرة في العناية الطبيعية.`,
  },
  {
    sort: 8,
    productName: "Mint Oil",
    description: "زيت النعناع",
    img: "assets/img/ment.jpg",
    category: "natural-oils",
    details: `زيت عطري يُستخدم للتدليك والروائح العطرية. له خصائص مهدئة ومنعشة.`,
  },
];
